//
//  AletterationPreferences.h
//  Aletteration
//
//  Created by David Nesbitt on 11-09-06.
//  Copyright 2011 David Nesbitt. All rights reserved.
//

#ifndef Aletteration_AletterationPreferences_h
#define Aletteration_AletterationPreferences_h

#define PREF_FIRST_TIME @"PREFERENCE_FIRST_TIME"
#define PREF_PLAYER_NAME @"PREFERENCE_PLAYER_NAME"
#define PREF_PLAYER_PORTRAIT @"PREFERENCE_PLAYER_PORTRAIT"
#define PREF_PLAYER_PORTRAIT_ORIENTATION @"PREFERENCE_PLAYER_PORTRAIT_ORIENTATION"
#define PREF_PLAYER_LETTER_COLOR_RED @"PREFERENCE_PLAYER_LETTER_COLOR_RED"
#define PREF_PLAYER_LETTER_COLOR_GREEN @"PREFERENCE_PLAYER_LETTER_COLOR_GREEN"
#define PREF_PLAYER_LETTER_COLOR_BLUE @"PREFERENCE_PLAYER_LETTER_COLOR_BLUE"
#define PREF_PLAYER_MUSIC_ENABLED @"PREFERENCE_PLAYER_MUSIC_ENABLED"
#define PREF_PLAYER_MUSIC_VOLUME @"PREFERENCE_PLAYER_MUSIC_VOLUME"
#define PREF_PLAYER_SOUND_ENABLED @"PREFERENCE_PLAYER_SOUND_ENABLED"
#define PREF_PLAYER_SOUND_VOLUME @"PREFERENCE_PLAYER_SOUND_VOLUME"
#define PREF_PLAYER_GAME_STATE @"PREFERENCE_PLAYER_GAME_STATE"

#endif
